-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDhcgCWbRuxoMapGI
X5hw26/Z/hxBNRMNDQ8K9mjDiICgCgYIKoZIzj0DAQehRANCAAQREkJbOJhhb3r9
4Mdpmqt8H+kdJvc6C06BNLiMegPF9ofkf9cR5bl2wZiAMKzCUu6vnsFyJDmowh3l
elUCe5IV
-----END PRIVATE KEY-----